### ISSUE TITLE
Vochain Explorer

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1]
Implement a block explorer for the Tendermint based Vocdoni blockchain (vochain).

There is an existing _old_ tendermint block explorer that might be useful to look at, the code can be [found here](https://github.com/vocdoni/vochain-explorer).

In order to test it locally a testsuit docker-compose can be started as shown in the [developer starting guide](https://github.com/vocdoni/docs/wiki).

The file `./src/store/modules/blockchain.js` of the vochain-explorer should be modified as follows:

```javascript
const state = {
  rpc: "http://127.0.0.1:26681",
```
Then the explorer can be compiled and executed:

```bash
yarn
yarn serve
```

The [tendermint RPC API](https://docs.tendermint.com/master/rpc/) should be used for basic blockchain information (validators, number of blocks, etc). 

And the [Gateway API](https://vocdoni.io/docs/#/architecture/components/gateway?id=api-definition) on websockets port 9090 should be used for specific Vocdoni information (such as getProcessList, getEnvelopeStatus, etc)

The block explorer should allow:
- [ ] search tx/block by hash
- [ ] see pending and already valid txs
- [ ] Clearly distinguish between different kinds of txs (by colour/name ?)
- [ ] see current blockchain height, hash, validators, block number, appVersion, Max block size, chainID (tendermint API)
- [ ] see the raw/json transactions contained inside a block (tendermint API)
- [ ] see voting process, entities, votes and results (Gateway API) --> Extended version (near future)

---

Basic information regarding the Vochain can be [found here (OUTDATED but mostly valid) ](https://vocdoni.io/docs/#/architecture/components/vochain).

A pure-go, nice framework, that could be used is https://github.com/gopherjs/vecty

![explorerMock](https://user-images.githubusercontent.com/17238033/86604692-ffc79380-bfa5-11ea-9f0f-97497931e3a5.png)

![vochainVis](https://user-images.githubusercontent.com/17238033/86606310-2090e880-bfa8-11ea-97ef-6b9dab249231.png)

- Go UI : https://github.com/go-graphics/go-gui-projects
- Gioui: https://gioui.org (probably the most modern framework, but maybe not yet ready for Webassembly)
- A nice explorer: https://blockscout.com/poa/core/

**Comment by NateWilliams2** [comment]
Issue in progress at https://gitlab.com/vocdoni/vocexplorer

**Comment by p4u** [comment]
Done at https://github.com/vocdoni/vocexplorer
