### ISSUE TITLE
bug: some error codes have changed without notice + some have incorrect prefixes

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-node#1000]
**Describe the bug**
The "election not found" error code has changed from 4046 to 4045 without notice in this commit 42823fb20d61096ddd32ca4e0c27db54bd2862a4 by @jordipainan 

Also, the new error introduced as 4046 seems more like a query validation error, than a not found error. For that reason I recommend using the `412` error prefix instead (precondition failed) for this specific validation/query error, or `400` (bad request). 

So two issues here:
- [x] election not found error has changed
- [ ] some errors have weird error prefixes, like the error for "election end date cannot be in the past", or "election end date must be after start date", "wallet private key already exists"... and probably more, would fit better in other error codes than in the current 404, like 400 or 412.

**To Reproduce**

Just take a look at commit 42823fb20d61096ddd32ca4e0c27db54bd2862a4, the file `api/errors.go` changed the error code of the "election not found" there.

**Current behavior**
Implementations using the old election not found code 4046 are now incorrectly parsing it. 

**Expected behavior**
To not change error codes unless it's strictly necessary

**Additional context**
- Bad request 400: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
- Precondition failed 412: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412

**Comment by altergui** [comment]
since this error code change never landed in stage yet, only in dev, i'd suggest to revert the change (thus AGAIN changing the codes, but this time back to what they were supposed to be always) so that when stage is redeployed, is like nothing happened

**Comment by elboletaire** [comment]
I don't know the implications of the rest of the commit if we revert only the error codes, plus I think we were planning switching dev to stg today, not sure if it would be on time (?)

**Comment by altergui** [comment]
also i'll add a header notice in error.go to instruct to only append errors, even if this leads to a messy order (i see that @jordipainan had the best intention, putting the ErrMissingParameter right next to the other ErrParam*, which would be the right thing to do in any other case)
it was my mistake to not include this notice in the original error.go

**Comment by altergui** [comment]
> I don't know the implications of the rest of the commit if we revert only the error codes, plus I think we were planning switching dev to stg today, not sure if it would be on time (?)

i believe the revert #1002 is trivial to review+merge, the other comments about the HTTP status codes i'd discuss them separately / another PR to allow this hotfix to land on time

**Comment by altergui** [comment]
>  * [ ]  some errors have weird error prefixes, like the error for "election end date cannot be in the past", or "election end date must be after start date", "wallet private key already exists"... and probably more, would fit better in other error codes than in the current 404, like 400 or 412.


regarding this, there's a misunderstanding: the HTTP Status Code returned along with those errors you mention *is indeed* 400 Bad Request

the fact that our internal error code is 404X for those errors is just a coincidence, the only number with some "meaning" is the first digit (`4` vs `5`), the other 3 digits are just random (incremental)

maybe it's worth it to clarify this somewhere? else i believe we can close this issue, since PR #1002 is merged

**Comment by elboletaire** [comment]
Oh, sad to see it's only the very first digit. I guess it can be closed then 😞 

Edit: yes I would clarify it, so others (like me) don't get confused again.

**Comment by altergui** [comment]
merged PR https://github.com/vocdoni/vocdoni-node/pull/1010 with this last clarification, so closing this issue
