### ISSUE TITLE
bug: wrong vote count may be wrong

### ISSUE THREAD

**Issue by selankon** [vocdoni/vocdoni-node#1021]
**Describe the bug**
As described on this interoperability issue the vote count may be wrong on vochain stats:

https://github.com/vocdoni/interoperability/issues/11#issuecomment-1558921185

> VoteCount seems to be reported wrong. It must be checked and tests must be added to assure it works as expected.
> It might have something to do with the size of the blockchain? In the current DEV network with +300k votes, it is returned wrong.

This bug was reported by @p4u and after discuss it on weekly meeting we decided to open this issue to check that everything  is fixed. Maybe @mvdan knows about this?

**Comment by altergui** [comment]
i just checked this and there's definitely something funny happening:

```
11-13 12:45 $ curl https://api-dev.vocdoni.net/v2/chain/info  -s | jq . |grep vote
  "voteCount": 3323,
11-13 12:45 $ curl -s http://miner1.dev.vocdoni.net:9090/metrics |grep vote_tree
vochain_vote_tree 3357
```

will dig into this

**Comment by altergui** [comment]
there's also a big divergence between process_tree and electionCount

```
 $ host=https://api-dev.vocdoni.net ; curl -s $host/metrics|grep process_tree ; curl -s $host/v2/chain/info|jq|grep electi
vochain_process_tree 279
  "electionCount": 545,
```

**Comment by altergui** [comment]
ok so i managed to reproduce this locally (using testsuite)

```
$ host=http://localhost:9090 ; curl -s $host/metrics|grep _tree ; curl -s $host/v2/chain/info|jq|grep Count
vochain_account_tree 44
vochain_process_tree 20
vochain_sik_tree 35
vochain_vote_tree 1252
  "electionCount": 286,
  "organizationCount": 71,
  "transactionCount": 1346,
  "validatorCount": 4,
  "voteCount": 1246,
```

and some conclusions:
 * vochain_vote_tree (state) includes overwritten votes in the count , while voteCount (indexer) doesn't. so if a vote is overwritten twice, vochain_vote_tree will increase by 3 while voteCount will increase just 1
 * electionCount (indexer) is much higher due to `indexer/archive.go:155 > new archive imported count=266`

**Comment by altergui** [comment]
so AFAIU the tiny difference seen in DEV network now (3357 vs 3323 votes), can be explained by those conclusions (overwritten votes)

i don't know how much was the difference when DEV network had 300k votes, so i'll let @p4u  decide whether to close this issue

**Comment by altergui** [comment]
closing this, i proposed an explanation for the difference observed
