### ISSUE TITLE
indexer: track accounts, balances and extend API

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1050]
The objective is to index accounts and their balances. 

So, we can implement a new API method to fetch the list of accounts `/accounts/page/:num`

```json
"accounts": [
{
  "address": 0x1234...,
  "balance": 123,
  "nonce": 1
 },
 "address": 0x3847...,
 "balance": 554,
 "nonce": 52
 }
 ....
```

Then we can use it in combination with the already existing transfers list for an account.: `/accounts/{accountID}/transfers/page/:page`

To this end, a proposed solution is to create a new table for accounts and balances:

```
CREATE TABLE accounts (
  account  BLOB NOT NULL PRIMARY KEY,
  balance        INTEGER NOT NULL,
  nonce INTEGER NOT NULL,
);
```

And modify the existing `token_transfer` SQL table to convert `from_account` and `to_account` to foreign keys.

```
CREATE TABLE token_transfers (
  tx_hash       BLOB NOT NULL PRIMARY KEY,
  block_height  INTEGER NOT NULL,
  from  BLOB NOT NULL,
  to    BLOB NOT NULL,
  amount        INTEGER NOT NULL,
  transfer_time DATETIME NOT NULL

FOREIGN KEY(....) ...
);
```

- [ ] Implement the SQL changes
- [ ] Implement the query for fetching the paginated list of accounts
- [ ] Implement the query for fetching the list of token transfers by `to_account` (see the existing `from_account`
- [ ] Implement a query to count the number of accounts
- [ ] Implement a query to count the number of transfers where the `to_account` is the provided address
- [ ] Implement a query to count the number of transfers where the `from_account` is the provided address
- [ ] Implement the API endpoint and APIclient method  `/accounts/page/:num`
- [ ] Implement the API endpoint and APIclient method  `/accounts/count`
- [ ] Implement `/accounts/{accountID}/transfers/count` to provide the total number of sent and received transactions
- [ ] Extend the current API endpoint `/accounts/{accountID}/transfers/page/:page` so it contains the `received` and `sent` transfers.
- [ ] Implement the unit tests of the indexer new queries
- [ ] Implement the integration tests into `test/api_test.go`
- [ ] Open the issue in Interoperability announcing the changes to the API, so the SDK and documentation can incorporate them

```json
"transfers": {
    "sent": Result of TokenTranfersByFromAccount (implemented),
    "received": Result of TokenTransfersByToAccount (missing)
  }
```

**Comment by p4u** [comment]
@jordipainan please review the issue :)

**Comment by jordipainan** [comment]
modified to include the nonce @p4u

**Comment by p4u** [comment]
@mariajdab have you started this issue? If not, maybe @mvdan could take care of it since he designed the indexer database from scratch and this week his queue is kind of empty.

**Comment by mariajdab** [comment]
> @mariajdab have you started this issue? If not, maybe @mvdan could take care of it since he designed the indexer database from scratch and this week his queue is kind of empty.

Sounds good, no problem. I started yesterday so I haven't made much progress on the task.

**Comment by p4u** [comment]
Let's see what @mvdan says about it

**Comment by mvdan** [comment]
I want to finish the breaking changes to the indexer schema while it's still fresh in my mind, but aside from that I should be able to move on to something else in a couple of days, yup. Happy either way.

**Comment by p4u** [comment]
just a friendly reminder of this missing issue @mvdan

**Comment by mariajdab** [comment]
#1135
