### ISSUE TITLE
Integrate process archive in the API backend

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1155]
When an election is queried, the API backend should:

1. Check if the chainID of the electionID matches its own, if so, return it from the current state/indexer
2. If its another chainID, then try to fetch it from the process archive

Things to consider:

- the process archive is currently an IPNS directory
- there could be more than 1 IPNS directory (multiple archives)
- we need somewhere to store the IPNS archives, maybe a remote HTTP file (could be a github json manifest) that is fetched by the gateway nodes
- the gateway should allow enabling/disabling the archive retrieval and specify a custom URL
- consider that the IPNS directories can be changed over time
- index locally the archive elections and use a goroutine to keep them updated
- when an election is returned and it comes from archive, there should be a boolean in the reply specifying it
- probably the indexer can take care of this task, it makes sense
- check our IPFS package, it contains most of the functions required for dealing with IPNS

**Comment by marcvelmer** [comment]
This probably affects the SDK, right?

**Comment by p4u** [comment]
Should not.

**Comment by p4u** [comment]
Well, only that you will have a new boolean on the API response indicating if the election is taken from the Archive or not.
