### ISSUE TITLE
Refactor main package for vocdoni-node

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1219]
The main and service packages are two of the oldest packages in the repository, and have accumulated a lot of technical debt.

+ https://github.com/vocdoni/vocdoni-node/blob/main/cmd/node/main.go
+ https://github.com/vocdoni/vocdoni-node/tree/main/service

A full refactor should be performed to make a cleaner and more maintainable code.  Ideally with some testing.

**Comment by mvdan** [comment]
Done with cmd/node for now, I think. I didn't spot anything in the service package right away. Let me know if there's anything in particular in the service package or its API that you think should be done better.
