### ISSUE TITLE
testing on indexer SQL migrations

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1243]
Ensure we the migrations work, between the release-lts-1 scheme to the new one defined in main branch.

Attached a SQL export of the "old" scheme that can be used for testing. 

[indexer.sql.gz](https://github.com/vocdoni/vocdoni-node/files/14100719/indexer.sql.gz)

**Comment by mvdan** [comment]
This was finished in d0d3161e1c13aac52b6b2654d9a60a3360c191c3, my bad for forgetting to link the issue.
