### ISSUE TITLE
bug: account search error 404 for existing account

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-node#1348]
**Describe the bug**
An existing account does not appear on searches.

**To Reproduce**

Accessing the account returns data, since it exists
```bash
curl -s 'https://api-dev.vocdoni.net/v2/accounts/38d2BC91B89928f78cBaB3e4b1949e28787eC7a3' | jq
```

Doing a search for that account returns 404:
```
curl 'https://api-dev.vocdoni.net/v2/chain/organizations/filter/page/0' --compressed -X POST -H 'Content-Type: application/json' --data-raw '{"organizationId":"38d2BC91B89928f78cBaB3e4b1949e28787eC7a3"}' | jq
````

**Comment by mvdan** [comment]
Any particular reason why you are mixing uppercase and lowercase letters? That might be tripping up the search. We could normalize the input for this.

**Comment by elboletaire** [comment]
Probably due to copying it from metamask, which gives it that way.

**Comment by jordipainan** [comment]
> Any particular reason why you are mixing uppercase and lowercase letters? That might be tripping up the search. We could normalize the input for this.

https://eips.ethereum.org/EIPS/eip-55

**Comment by p4u** [comment]
Yes, we should normalize it.

**Comment by p4u** [comment]
can yu take it @mvdan ?

**Comment by mvdan** [comment]
Ah I didn't know this, SGTM. Yes, I'll do a fix.
