### ISSUE TITLE
Add Prometheus service to testsuit

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#141]
Extend the docker-compose file to include a Prometheus + Grafana service to automatically monitor the testsuit containers.

It will be very useful for having a visual representation of what's happening when executing performing tests and benchmarks on the testsuit.

**Comment by vdo** [comment]
https://github.com/vocdoni/vocdoni-node/commit/fff779b5f01e9431270723a5df4f3c09f4fa078d
