### ISSUE TITLE
feature: move multirpc to vocdoni-node

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#155]
**Describe the feature**
Move the multirpc repository from https://github.com/vocdoni/multirpc to this repository

**Motivation**
Have a monorepo which is easy to maintain and avoid cyclic dependencies.

**Proposal**
Copy&Paste the current multirpc to `vocdoni-node/multirpc`

**Components affected**
vocdoni-node vocdoni-manager blind-ca multirpc

**Constraints & Assumptions**
All paths from vocdoni-node and multirpc need to be adapted.

**Comment by emmdim** [comment]
Please ping on this thread before closing the issue: https://github.com/vocdoni/vocdoni-manager-backend/issues/36
Thanks
