### ISSUE TITLE
feature: improve scrutinizer.WalkEnvelopes use of block cache

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/vocdoni-node#187]
**Describe the feature**
WalkEnvelopes executes a callback on each envelope belonging to a given process. To fetch each envelope, it loops through all VoteReferences belonging to a given processId in the badgerhold database. It then fetches the vote transaction referenced by this VoteReference, which includes loading the entire block containing that transaction, either from the database or the block cache. 

This is an inefficient use of the LRU block cache. VoteReferences are not sorted by block height, meaning one block could include transactions at various points in our loop through VoteReferences. For a process spanning a sufficient number of blocks, and with a small block cache size, we could easily load a block X to the cache to fetch a vote transaction it contains, load a bunch of other blocks and kick X from the cache, and then load block X back into the cache to fetch another vote transaction it contains. This could happen many times. Ideally, each block should only be loaded to the cache a maximum of 1 time during this process, and all of its vote transactions should be fetched before it's removed from the cache.

**Proposal**
One of the following
- sort the VoteReference query by block height: `badgerhold.Where("ProcessID").Eq(processId).Index("ProcessID").SortBy("Height")`

Using badgerhold, this would likely be a worse trade-off for performance.

- increase the size of the block cache

This would improve the situation, but the issue would still apply for sufficiently large processes.

- something else more complicated 

**Components affected**

Scrutinizer

**Constraints & Assumptions**

Our use of badgerhold is a constraint here. It may be worth it to revisit this issue once we've moved to a different/improved database design.

**Comment by mvdan** [comment]
I actually don't think adding a `SortBy` at the end of the query should make badgerhold significantly slower. Badgerhold will pull the entire list of records into a slice in memory, so it's already at least linear cost over the number of votes. Sorting is most likely `n * log(n)` unless they have another really bad bug, so I doubt it would significantly affect performance.

But I also agree with you that maybe we should wait until we have a performant database first. Optimizing the block cache when the DB queries are pretty slow might not make much sense :)

**Comment by NateWilliams2** [comment]
I've done some benchmarking testing of WalkEnvelopes with SortBy...

| # of Envelopes | Normal times | times with SortBy | 
--- | --- | ---
|  20 | 3ms, 4ms | 4ms, 4ms |
| 200 | 29ms, 26ms | 56ms, 27ms |
| 9998 | 1369ms, 894ms | 2117ms, 1292ms |
| 14239 | 3009ms, 1428ms | 1744ms, 1878ms |

obviously a sample size of 2 isn't enough to draw clear conclusions, but I don't see any large negative effect here.
