### ISSUE TITLE
feature: rename and extend getProcessMeta()

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#203]
**Describe the feature**
In order to make getProcessMeta() useful for the client, we'd need to extend the fields to:

- metadata
- startBlock
- endBlock
- sourceNetworkId
- entityIndex

Also rename getProcessMeta to getProcessHeader

**Motivation**
Make client more efficient.

**Comment by brickpop** [comment]
@NateWilliams2  It would also be nice to repurpose the `type` field. Currently it features a string with terms like `encrypted single`.

To make it easier to consume, it would be nice to export these individual fields like `{ encrypted: false, single: true, ... }` or similar.

--

Also, for consistency, we are using `startBlock` and `blockCount` elsewhere. Not critical at all, but maybe it makes sense to try to unify this.

**Comment by brickpop** [comment]
Also @NateWilliams2 I have one question, what does `height` mean?

![image](https://user-images.githubusercontent.com/4456749/119549456-87251d80-bd97-11eb-9836-78640e350518.png)

**Comment by NateWilliams2** [comment]
@brickpop height is the height of envelopes for that process. It's the generic height field for any request, I could add a new field for envelopeCount

**Comment by brickpop** [comment]
Also @NateWilliams2 would it be possible to rename `state` to `status`? :)

**Comment by brickpop** [comment]
> @brickpop height is the height of envelopes for that process. It's the generic height field for any request, I could add a new field for envelopeCount

Ok, maybe it is more helpful to write it like `envelopeHeight` or something like this... but otherwise, we can simply rename on the library

**Comment by p4u** [comment]
no renamings please... we can break many things

**Comment by p4u** [comment]
@brickpop if you have suggestions for API rename, let's open another issue.

@NateWilliams2 lets not do breaking changes on the API, so let's revert all renamings. Everything which is not related to getProcessMeta() should not be included in the PR of this issue.
