### ISSUE TITLE
feature: investigate gossipsub

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#245]
**Describe the feature**
Investigate if we can use gossipsub instead of our custom implementation subpub

**Motivation**
Improve the behavior of the pubsub message for ipfsSync

**Comment by altergui** [comment]
leaving here a couple of references on where to start
* https://github.com/libp2p/specs/tree/master/pubsub/gossipsub
* https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go

i will play a bit with this and maybe take a stab at implementing it, see how far i can get :)

**Comment by altergui** [comment]
i explored this possibility of DHT discovery + gossipsub, mixing the example code from
* https://github.com/libp2p/go-libp2p/tree/master/examples/chat-with-rendezvous
* https://github.com/libp2p/go-libp2p/tree/master/examples/pubsub/chat

the resulting code is a hasty copy-paste mess but compiles and exchanges "hello world" messages, both by broadcast (using the GossipSub topic) and by unicast (using streams between discovered peers)
https://github.com/vocdoni/vocdoni-node/compare/master...altergui:sandbox/gossipsub

it doesn't interact in any way with ipfs or pinning: i removed all the PubSub init and i just focused on reaching a "hello world" using gossipsub. so right now my branch is not only ugly but also useless, just an exploration. but i pushed it out of my local git repo FWIW.

**Comment by altergui** [comment]
implemented and merged
