### ISSUE TITLE
Add tree.Size using arbo.GetNLeafs

### ISSUE THREAD

**Issue by arnaucube** [vocdoni/vocdoni-node#271]
Implement tree.Size method using [arbo.GetNLeafs](https://github.com/vocdoni/arbo/blob/master/tree.go#L837)

Depends on having https://github.com/vocdoni/arbo/issues/17 implemented.

**Comment by jordipainan** [comment]
any updates on this @arnaucube or can be closed ?

**Comment by arnaucube** [comment]
Right, it was done here: https://github.com/vocdoni/vocdoni-node/commit/9e180a06caad4fc5c170bf234315c022109b6a5d#diff-cc0232c91308d76ea39707247092fa4614a5fa2b8b881dc7a6accd32f75950fe
