### ISSUE TITLE
feature: Use /tmp as tmpfs in github workers

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#285]
I believe that the environment in which the test run in the github workers doesn't have /tmp mounted as tmpfs.  If that's the case, I think we could benefit from having /tmp as tmpfs as there are a few tests that work with databases that are stored in a temporary directory under /tmp.  That should increase the github actions test speed.

**Comment by vdo** [comment]
This has been enabled in both CI servers.

BTW, please create devops tasks in the dedicated Jira project rather than in Github Issues
