### ISSUE TITLE
feature: Store circuit artifacts in a path set by config

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#288]
Currently the circuit artifacts (Vk) is stored in a path relative to the PWD from which the node is run.  I think it would be much cleaner to store the artifacts in a path set by configuration, for example, somewhere under `VochainCfg.DataDir`.

**Comment by jordipainan** [comment]
@arnaucube can you update on this?

**Comment by altergui** [comment]
i fixed this in 7c854c5fe950bee228a657ab49a20b1cc2ce47e6
