### ISSUE TITLE
bug: Sometimes compose-test fails with "process keys is empty"

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#299]
**Describe the bug**
For the past month or so, from time to time (I'd say between 1/5 and 1/10) the compose-test fails with this error:
```
2021-10-04T14:51:54Z	FATAL	vochaintest/vochaintest.go:361	[http://gateway:9090/dvote] process keys is empty
main.mkTreeVoteTest.func1
	go.vocdoni.io/dvote/cmd/vochaintest/vochaintest.go:361
```
[logs_2215.zip](https://github.com/vocdoni/vocdoni-node/files/7284186/logs_2215.zip)

**Comment by mvdan** [comment]
This sounds like some form of race; perhaps vochaintest fetches the process keys before they are ready. If it were a true backend bug, I imagine the backend would be returning or logging some form of error.

**Comment by altergui** [comment]
i bumped into this several times while working on the CI, so i'll dig into it

**Comment by altergui** [comment]
i'm chasing this one, since on the branch i'm working, it's happening 7 times out of 10
(all of the failures are the same error, process keys never appear)
![image](https://user-images.githubusercontent.com/2815267/192602248-0b738286-9b7e-436e-ae6e-187e6d30635e.png)

**Comment by altergui** [comment]
catched it! the process ends up with empty keys when `rejected tx: adminTxCheck: cannot add process keys to a process that has started or finished status (READY)`

i.e. startBlock is too near in time, and by the time process keys are to be added, it already started.

https://github.com/vocdoni/vocdoni-node/actions/runs/3138070184/jobs/5103477505#step:3:8215
```
miner1_1    | 2022-09-27T18:45:38Z	DEBUG	vochain/transaction.go:599	checking admin signed tx {"txtype":"ADD_PROCESS_KEYS","processId":"VzThEAPFzOwsLWWCYfvcQLBP7AbUkFckLTkBBAAAAAE=","encryptionPublicKey":"Bbu9as36F8x+P7nUDpEjqdcEezOz6NpuIlaQime3CSk=","keyIndex":4,"nonce":128863522} by addr f7fb77ee1f309d9468fb6dcb71add0f934a33c6b
miner1_1    | 2022-09-27T18:45:41Z	INFO	service/vochain.go:230	[vochain info] height:30 mempool:3 peers:9 processes:4 votes:600 vxm:0 voteCache:0 blockTime:{1m:7.50}
miner1_1    | 2022-09-27T18:45:45Z	DEBUG	vochain/app.go:610	deliver tx: {"admin":{"txtype":"ADD_PROCESS_KEYS","processId":"VzThEAPFzOwsLWWCYfvcQLBP7AbUkFckLTkBBAAAAAE=","encryptionPublicKey":"Bbu9as36F8x+P7nUDpEjqdcEezOz6NpuIlaQime3CSk=","keyIndex":4,"nonce":128863522}}
miner1_1    | 2022-09-27T18:45:45Z	DEBUG	vochain/transaction.go:599	checking admin signed tx {"txtype":"ADD_PROCESS_KEYS","processId":"VzThEAPFzOwsLWWCYfvcQLBP7AbUkFckLTkBBAAAAAE=","encryptionPublicKey":"Bbu9as36F8x+P7nUDpEjqdcEezOz6NpuIlaQime3CSk=","keyIndex":4,"nonce":128863522} by addr f7fb77ee1f309d9468fb6dcb71add0f934a33c6b
miner1_1    | 2022-09-27T18:45:45Z	DEBUG	vochain/app.go:612	rejected tx: adminTxCheck: cannot add process keys to a process that has started or finished status (READY)
```

**Comment by altergui** [comment]
this bug is ...undead

https://github.com/vocdoni/vocdoni-node/actions/runs/3369241751/jobs/5588669006#step:3:10769
```
miner6_1    | 2022-11-01T12:20:12Z	DEBUG	vochain/app.go:491	checkTx error: newProcess: cannot add process with start block lower than or equal to the current height
```
[logs_4466.zip](https://github.com/vocdoni/vocdoni-node/files/9909796/logs_4466.zip)

don't think it's worth it to dedicate more time right now (i'd look into #645 first) but wanted to note my fix was not enough.

**Comment by altergui** [comment]
vochaintest is deprecated and being replaced by end2endtest
so this undead bug will die along with vochaintest. although this didn't happen yet, i'm closing this issue since we won't work on it
