### ISSUE TITLE
Rethink the db interface regarding Txs & Batches

### ISSUE THREAD

**Issue by arnaucube** [vocdoni/vocdoni-node#328]
Initially started by @ed255 in https://github.com/vocdoni/vocdoni-node/pull/319#pullrequestreview-787822809 :
> [...] currently we have a messy design for the Database implementation with Pebble because our current Database implementation has Transactions and Pebble doesn't have transactions. So with Badger a db.WriteTx is a badger.Transaction but in Pebble a db.WriteTx is a Batch.
> 
> Moreover, on the reading side, Badger requires a ReadTx to read, but Pebble doesn't, and our Database interface uses ReadTx.
> 
> So we have two implementations that behave very differently.
> 
> And then we introduce the Apply, which in my opinion, makes sense for a Batch but not for a Transaction. A Transaction is more than a list of writes; it also keeps a point in time where the Tx was started, and every pending write has associated with it the value found in the DB before the Tx was started. A Batch doesn't have this.
> 
> I think we could implement a Batch type which just accumulates writes and deletes, and allows reading from an underlying Database / ReadTx, and then can be Committed by applying all the reads and writes to a new WriteTx. For Pebble we would just wrap the Batch type, for Badger we would create a new type with all the necessary fields. And a proper Batch is what Arbo should use in this case.

Currently arbo only needs batch features, does some part of vocdoni-node need tx features? If that's not the case we could 'migrate' from txs into batch.

**Comment by jordipainan** [comment]
@arnaucube seems that we can close this ?

**Comment by arnaucube** [comment]
Right, this was done and currently the db package works with 'batch' instead of 'tx'.
