### ISSUE TITLE
Remove Locking in State.Close

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#330]
Currently `State.Close()` tries to acquire a lock on `State.Tx` before Discarding the `Tx`.  It's common to have `State.Close()` as a cleanup / defer.  If there's a panic in another place after acquiring the `Tx.RWMutex` and before releasing it, the process will deadlock in the `State.Close()` when trying to acquire the `Tx.RWMutex`, and then we don't see the panic.   By removing the `Lock` in `State.Close` we avoid this situation.

**Comment by altergui** [comment]
i don't see any `defer State.Close()` in our current codebase (except in unit tests), so i'm closing this
