### ISSUE TITLE
bug: PreRegister design doesn't check for double preRegister

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#333]
The current design and implementation of the PreRegister doesn't check that the same user from the pre-census registers more than one zkCensusKey in the rolling-census.

I propose that we add a new subTree for the process with PreRegister that sets which users in the pre-census have registered a key in the rolling-census.  This hew subTree would use the pre-census userID (public key) as the tree key.

**Comment by p4u** [comment]
Take into account that we will need weighted voting in some moment, so a user should be able to register more than one key. For instance, a user has a weight of 10, thus she can register 2 keys or weight 5.

**Comment by ed255** [comment]
I see.  We could keep track of the "weighted used" (as a value on the new subTree), but right now in a PreRegister Tx I don't think there's any field requesting how much weight you want to assign to that zkCensusKey.

I would suggest we complete first the rolling census as needed for anonymous voting without weights, and after that we extend it with weights, because I think there are more parts that will require updates, not just this preRegister subTree.

**Comment by p4u** [comment]
> I would suggest we complete first the rolling census as needed for anonymous voting without weights, and after that we extend it with weights, because I think there are more parts that will require updates, not just this preRegister subTree.

Agree
