### ISSUE TITLE
feature: Add support for checking Tx Status

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#340]
Currently there's no endpoint to check the status of a tx, so in general, the user only knows if the tx enters the mempool or is discarded immediately; but the user doesn't know when and if this tx is ever mined.

For the envelope tx there's a special endpoint to check the status.  If we want to add support for checking the status of other txs with a new endpoint for each tx type, it will become cumbersome, specially if we want to keep adding new txs types.

For anonymous voting we already have a new tx type that would benefit from this: registerKey (otherwise, the user can't confirm if the pre-registration step succeeded or not).  Other new tx types would also benefit from this, like transfer tx.

**Comment by p4u** [comment]
How would you propose to implement this? We need some kind of transaction identifier (which might be a hash of the payload) but then we also need a fast and efficient way to determine if a transaction has been included in the State or not. So we either rely on Tendermint blockstore or we build our own statedb tree with transaction hashes.

**Comment by ed255** [comment]
I would try to use the Tendermint blockstore as much as possible.  It would be ideal if the TxHash could be computed by the client as well.  We would need to check if the Tendermint blockstore indexes transactions by a TxHash or another unique identifier that can be computed before the Tx is mined.

If the client can't compute the TxHash, then we could always return it from the node upon submitting any kind of Tx.

**Comment by p4u** [comment]
Actually if we want to be able to get a transaction by the hash using the Tendermint blockstore, we have to enable the "tendermint tx indexer" which we disabled long ago cause it requires a new database and a lot of extra disk space. TBH I'm  agasinst enabling this tendermint piece again... its too overkill/overhead, so we must find another solution.

I think we implemented already this indexing on the scrutinizer package but I'm not sure. At least we had this conversation in the past. Can you help here @NateWilliams2 ?

**Comment by NateWilliams2** [comment]
We index transactions with the following struct: 
```go
// TxReference holds the db reference for a single transaction
type TxReference struct {
	Index        uint64 `badgerholdKey:"Index"`
	BlockHeight  uint32
	TxBlockIndex int32
}
```
The use case for this is pagination of all transactions: if I want transaction 3401, I can find the `TxReference` with that index, and then get the `BlockHeight` and `TxBlockIndex` to retrieve the transaction itself from the App. The hash itself is not actually stored. It's generated when adding the TX to the mempool, and it can be generated from the tx bytes itself.

In order to track TXs like you propose, we could add a Hash to the TxReference. we would have to re-calculate the hash of the tx bytes on every single TX in the scrutinize when indexing it.

**Comment by NateWilliams2** [comment]
I don't think it's that crazy of a resource usage in terms of storage or processing- I'd be happy to write a PR enabling this, and we could run some benchmarks if worth it. THoughts @p4u @ed255 ?

**Comment by p4u** [comment]
Go ahead. Make a proposal and lets see what are the implications :)
