### ISSUE TITLE
dvote-js registerKeyTx fails

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#353]
dvote-js snark proof fails with "inputs values not inside Finite Field"

```
2021-11-07T00:03:10Z	DEBUG	vochain/app.go:415	rejected tx: inputs values not inside Finite Field
2021-11-07T00:03:10Z	DEBUG	vochain/app.go:413	deliver tx: {"registerKey":{"nonce":"c5uPj9JwoBs9xEUj0z101UpkwDsPmMwvtA65A5E4xyo=", "processId":"Q3E/LJ1SsW3tXPAQseQv1U1VgmmFF6tI86qtTwcI5x0=", "proof":{"arbo":{"type":"BLAKE2B", "siblings":"pQABAB/+bhecw2Hg04koqjp1ODs6aW6AtA/RnK0Ym2x36UVXMMmZ59GcmLuw4ppLlQcOO6xgtEr7Vi/358kX7cHzQIw5Pu5npYMHbBEZCUNO+BEHHjGQvMb8Tvg5fdyKkgFW3e7gMLwcNhT7bkBlDgYiqD6xOotGQt48HZ9O5wMSBP1WrPs6zbRnU7uDVA63RhEJTEqZY5QZqiW1qGcJFI1FUrrF"}}, "newKey":"EikIPmrwSiJXWMDauSwbSJFlkHetsglaDBlMj1UQqeM=", "weight":"AQ=="}}
```

**Comment by brickpop** [comment]
Sending the following transaction:

```json
{
  "method":"submitRawTx",
  "payload":"CtkJCtYJCiCcxqvqeY53qyuvIZiuOp+VBzeKSbPvOMgE67p9MfLUVRIgPok3vp5P4cdRQn8IIK1p8E2aeGeaIvFLBiR5OkU/pwkavAc6uQcSTDc2MTg0OTk0MDQ0MDUxMjYwODQzOTk5OTUwMjcyNjIyMDM1MDA0Njk2MzE5NDk5MjkzMDM5MzU5NTAzNTg2NTA4OTE2NzMyNzI2NDYSTTE3Nzg4MDE3NDg1OTY1NjcwMjExNjI2NzYxMDU2ODE4ODk2ODM4NDIzOTA3OTk5MTczOTYzMzc2NTE2MzY1Nzc1NzU0NDMyNjczMjYwEgExGk0yMDUwOTY2Njk4MzA0MDY1MTg5MzkxNjU1MjkwNzY4MTc1MzgxMjM5ODA1NDY2OTE5MjY3NzM4NzAzNTc2Nzc1MjEyODUyMzczODU4NhpNMTg2NDQzNzUwNDIyNjIxNTUwODIyNDk5NDQ4MzQ0Mjg2NDcyODk5NzU1NDUzNzU4MTk2ODU…cxODUwNjA0MTU1ODU5KicxMDYzODk1MDM2MjQwMjA1NDU5OTQzNDc2NjQ5MzIyMjQyMTI2ODAqJzI2MzkxMTY5NDk0NjcwOTkzMjAyMjY4NTM1Nzk2MzYxNDQ2NDUwMSKIAS6gBine7D5MbH7fPjcd/t26HlULejvfuU5IYglLMbYcjwXK+5BJd9TKlHjuWy9KI/sBWdTwGzc5Jcvb5beTnim7VtOw8gpiIuI3YQ29MoIF7lCUFN1VHqO7KT0O0mmgnqDSjHPjuiCCx6IOpG7jWdUNPSONQPNXWtRoQHrpXp87fk6z6/jKrO4qQjB4MTczNWYzMDQ1NWQyYzEzMTVkOTA5MTFmOGU0ZDQwNjliM2NlNGI4YzZmYWY1ZTcyZTMxMTA2MzEyYjgyZDNkMzICAQISQTyqS/4SzoT6llqtiJH5AB42Lh/w/iVuxoJyzBwqQ5NXHisVhDQoyD3Qjz7bNIEls6mSCMPxNHLYFVhj7X0Oax4b"
}
```

Response: 
```
message:'616464547820766F74655478436865636B3A206572726F72206F6E207A6B50726F6F6620666F726D6174
```

(hex decoded as `addTx voteTxCheck: error on zkProof format`)

**Comment by p4u** [comment]
Some registerKey transactions succeed, such as:

```
2021-11-07T00:12:21Z    DEBUG    vochain/app.go:413    deliver tx: {"registerKey":{"nonce":"YXowRuiDmPqws5hucua5HziOK20t9Qq8oI6Pp3KG29o=", "processId":"Pok3vp5P4cdRQn8IIK1p8E2aeGeaIvFLBiR5OkU/pwk=", "proof":{"arbo":{"type":"BLAKE2B", "siblings":"5QABAH+ZSltbld+cQQSw1nOifF4sWFsPRXS/URedbZrAxSILclaHxXtbaeGaPLxProWjAxfUHLY114vR3KvzLDTsgLSXHiOlKCilm6meJd+50JgNCnLp+U0Bdry3uleQEnhb7qUjGhruOxYvhJBMq91/tBvv7fvtUaYjImjA/IKwmiuL0kj3mXupdnx4ZYbntbiAzND4O4PO3UckBKiJBVQjf8SHyEYzxeZog03Ve2qPRw4VDlxOcGE4hYSLsvdZ2C0uOzTCqYBMD5uqRbPZEsBu2NzT1h7wzdk/QnFjKvSfuHda3A=="}}, "newKey":"FO55MFxCOM2Iged+0TvJCpzGl009moYB9MyQOBgubw8=", "weight":"AQ=="}}
```

**Comment by p4u** [comment]
```
2021-11-07T00:42:08Z	DEBUG	vochain/app.go:415	rejected tx: cannot add (1d402cc5be87f99e9b0ff9cf6da15e42d37cbe818090c696a966901399e7f5d3) to rolling census: inputs values not inside Finite Field
```
The error comes from line https://github.com/vocdoni/vocdoni-node/blob/master/vochain/census.go#L53

**Comment by p4u** [comment]
The problem might be the Endianess used by the Poseidon go-lang implementation, maybe different of the javascript one.

**Comment by p4u** [comment]
@arnaucube

**Comment by arnaucube** [comment]
> dvote-js snark proof fails with "inputs values not inside Finite Field"
> 
> ```
> 2021-11-07T00:03:10Z	DEBUG	vochain/app.go:415	rejected tx: inputs values not inside Finite Field
> 2021-11-07T00:03:10Z	DEBUG	vochain/app.go:413	deliver tx: {"registerKey":{"nonce":"c5uPj9JwoBs9xEUj0z101UpkwDsPmMwvtA65A5E4xyo=", "processId":"Q3E/LJ1SsW3tXPAQseQv1U1VgmmFF6tI86qtTwcI5x0=", "proof":{"arbo":{"type":"BLAKE2B", "siblings":"pQABAB/+bhecw2Hg04koqjp1ODs6aW6AtA/RnK0Ym2x36UVXMMmZ59GcmLuw4ppLlQcOO6xgtEr7Vi/358kX7cHzQIw5Pu5npYMHbBEZCUNO+BEHHjGQvMb8Tvg5fdyKkgFW3e7gMLwcNhT7bkBlDgYiqD6xOotGQt48HZ9O5wMSBP1WrPs6zbRnU7uDVA63RhEJTEqZY5QZqiW1qGcJFI1FUrrF"}}, "newKey":"EikIPmrwSiJXWMDauSwbSJFlkHetsglaDBlMj1UQqeM=", "weight":"AQ=="}}
> ```

But in these logs, it indicates that the proof is of type `BLAKE2B`. When this type of tree is used, should not give any errors of finite fields neither Poseidon related stuff, as blake2b is not related with that.

**Comment by p4u** [comment]
The problem is not with the proof, but with the "newKey" registration for the rolling census, see my comments above.

**Comment by arnaucube** [comment]
For the anonymous-voting circuits repo we have code in js & go where a Poseidon hash is computed and is working fine:
- js: https://github.com/vocdoni/zk-franchise-proof-circuit/blob/master/src/franchise.js#L46
- go: https://github.com/vocdoni/zk-franchise-proof-circuit/blob/master/test/go-inputs-generator/census_test.go#L94

Could you please point me to the js code that generates the poseidon that the backend does not accept?

**Comment by arnaucube** [comment]
Now talking with @brickpop , seems that the problem could be between the encoding in client side and decoding in backend side of the output value of the poseidon hash.

**Comment by brickpop** [comment]
```ts
        const hexHashedKey = Poseidon.hash([secretKey]).toString(16)
        const newKey = hexHashedKey.length % 2 == 1 ?
            utils.zeroPad("0x0" + hexHashedKey, 32).reverse() :
            utils.zeroPad("0x" + hexHashedKey, 32).reverse()

        // Then

        const registerKey: RegisterKeyTx = {
            newKey,
            processId: Buffer.from(strip0x(processId), "hex"),
            nonce: Random.getBytes(32),
            proof,
            weight: Buffer.from(strip0x(weight), "hex")
        }

        const tx = Tx.encode({ payload: { $case: "registerKey", registerKey } })
        const txBytes = tx.finish()

```

**Comment by arnaucube** [comment]
Is this solved now?

**Comment by jordipainan** [comment]
yep
