### ISSUE TITLE
bug: compute public input vote hash when verifying a snark proof of a vote

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#356]
See https://github.com/vocdoni/vocdoni-node/blob/b68e96d58c571a2006c6ab85c0003f02d0033545/vochain/transaction.go#L179

We are building the public inputs with a vote hash sent by the user, and we don't check that this vote hash matches the vote sent by the user!  The user shouldn't send the vote hash, it should be computed in the vochain from the vote package.

**Comment by arnaucube** [comment]
Yes, we talked about this last week, I did the change locally, now it can be found in this branch https://github.com/vocdoni/vocdoni-node/tree/feature/zkcensus-update-processId (had it locally until now as I'm finishing the unit test which depends on some stuff from snarkjs that is not working).
The hash is done at backend side, and that value is the one used as public input for the proof verification.
