### ISSUE TITLE
bug: Use the anonymous vote nullifier to avoid double voting

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#358]
We are not marking the nullifier (the one from the circuit inputs) as used when registering an anonymous vote!  We need to index each vote data by it's nullifier to avoid the double vote.

Currently in anonymous voting we have nullifier in two places: publicInputs for the circuit and Vote.Nullifier.  And there are APIs that work with the "old" nullifier.  Maybe we could unify them.

**Comment by arnaucube** [comment]
Related: https://github.com/vocdoni/vocdoni-node/pull/362
