### ISSUE TITLE
bug: panic when siblings are not in the correct format in submitRawTx

### ISSUE THREAD

**Issue by emmdim** [vocdoni/vocdoni-node#377]
While testing other issues i was sending the the submitRawTx with siblings in a string format (after having casted as string from the result of the `genProof` call). This caused the gateway to panic with a message: `fatal error: runtime: out of memory`

Attaching log
[message.txt](https://github.com/vocdoni/vocdoni-node/files/7598447/message.txt)

**Comment by jordipainan** [comment]
@emmdim i think this was solved right ?

**Comment by altergui** [comment]
never heard of this again, closing
