### ISSUE TITLE
State isQuery flag should be renamed

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#382]
**Motivation**
In the vochain State, `isQuery=true` means the committed State should be queried, and `isQuery=false` means the uncommitted state should be queried.
the word Query comes from Tendermint Query ABCI and is merely an implementation detail.

**Proposal**
Rename the isQuery flag to `committed`. So functions will look like
```
state.Oracles(committed=false)
state.VoteCount(committed=true)
```
which is more obvious, and doesn't require explanation.

**Comment by G10h4ck** [comment]
I am working on it with this PR https://github.com/vocdoni/vocdoni-node/pull/490

**Comment by G10h4ck** [comment]
PR https://github.com/vocdoni/vocdoni-node/pull/490 has been merged fixing the issue
