### ISSUE TITLE
Handle ZK proof public signals without requiring client side mangling

### ISSUE THREAD

**Issue by brickpop** [vocdoni/vocdoni-node#395]
For tactic reasons, the following wirkaround has been left in place temporarily:
https://github.com/vocdoni/dvote-js/pull/77/files#diff-f97d546d14b4dc0a8532321b0944b357bcca051acb16315994ed081a74b404a6R149

Instead of requiring clients to alter the output public signals of groth16, the Vochain should handle the public signals with its own data, or at least accept the groth16 parameters as they are

**Comment by jordipainan** [comment]
@arnaucube any updates?

**Comment by arnaucube** [comment]
I guess that it was covered in https://github.com/vocdoni/vocdoni-node/pull/415 & https://github.com/vocdoni/dvote-js/pull/84 , so, if @brickpop agrees we could close this issue.
