### ISSUE TITLE
panic on ipfsSync

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#421]
```
2021-12-22T16:55:54Z	DEBUG	ipfssync/ipfssync.go:216	broadcasting message UPDATE {Address:Qmc9fTnnzmWNe6BHkmSTaDwDwCWVT9WsMfwFnwDMa9S9bJ Hash:babad5748132954889375b6c293248fcd35e279006e19873e2b7d5a5fa32b2bc MA: PL:[] Ts:1640192154}
2021-12-22T16:55:54Z	DEBUG	subpub/gossipsub.go:80	gossiping 90 bytes to peers in topic ff86804e95810819a8c1eac23d1a0c303ae47afc07d89d12c684c28ff5fd68a7: [QmZWDjQkzPMyuw3d898CX9JerkfcycPUSPgQduZvx9jsgk]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x246042c]

goroutine 182800 [running]:
go.vocdoni.io/dvote/ipfssync/subpub.(*SubPub).readHandler(0xc004a88dc0, {0x30f01c0, 0xc006b3f4a0})
	go.vocdoni.io/dvote/ipfssync/subpub/stream.go:74 +0x2ac
created by go.vocdoni.io/dvote/ipfssync/subpub.(*SubPub).handleStream
	go.vocdoni.io/dvote/ipfssync/subpub/stream.go:27 +0x196
```

**Comment by altergui** [comment]
:roll_eyes: :stuck_out_tongue: thanks for reporting, will dig into this

**Comment by altergui** [comment]
ok, sorry about this. it was introduced at the very last (squashed) commit, i added a couple of lines in `ipfssync/subpub/stream.go:74` to treat specially the "stream reset" and make it output something prettier on the logs. but forgot to check first for `err != nil` :facepalm: 
i'll prepare a hotfix asap.

**Comment by altergui** [comment]
what intrigued me the most is ..how i did not notice this??
so i reviewed my test scenario and understood that i was using this crazy complex `testground`, which i set it up to pull the code from [my repo](https://github.com/altergui/vocdoni-node/commit/a853502a1a17d07d37a3ae9a1b6ea940e63242d1) and i forgot to push this last commit when doing the testing. So, mystery solved, and i'm properly testing everything now the hotfix :+1:

**Comment by altergui** [comment]
fixed and tested properly, with 10 nodes on a local `testground` and one more remote node in a VPS.
