### ISSUE TITLE
bug: `dvotecli genesis` generates a genesis with empty treasurer

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#424]
since this commit
https://github.com/vocdoni/vocdoni-node/commit/187c471a33d4f22237e0a9d23dfca9ae51862523#diff-088e50f432c8393ca86f7bb7c1054fbd1867eef3d5e25e8773d0dbeabf7bc8adR354
dvotenode will not start if the `genesis.json` doesn't have a valid address in `treasurer`.

the hardcoded genesis.json in `vochain/genesis.go` does specify a hardcoded value (`0x309Bd6959bf4289CDf9c7198cF9f4494e0244b7d`)
but the `dvotecli` produces a genesis with `"treasurer": ""`
and if this `genesis.json` is used, `dvotenode` fails to start

**To Reproduce**

- Steps to reproduce the behavior:
  1. generate a genesis.json using
  ``` 
  dvotecli genesis \
          --chainId {{chain_id}} \
          --seeds {{seeds}} \
          --oracles {{oracles}} \
          --miners {{miners}}
  ```
  2. copy-paste the relevant output and save it as `genesis.json`  
  3. run `dvotenode` with that `genesis.json`
  4. `dvotenode` dies with `treasurer should be a valid Ethereum address: %!s(<nil>)`

i imagine two solutions:
* either set a default value for `treasurer` (maybe `0x0000000000000000000000000000000000000000`?) in `cmd/dvotecli/commands/genesis.go` (current default is "")

* or make `dvotenode` (`vochain/app.go`) continue gracefully in case `treasurer` equals the empty string

but i can't decide which one is the reasonable, since i'm totally lost on what a treasurer is.

**Comment by jordipainan** [comment]
The treasurer is a key piece for the ethereum-less approach as is in charge of minting and set transaction costs so IMO this is something that should be defined in the genesis. I changed the dvotecli for throwing an error if the treasurer is not set.

**Comment by jordipainan** [comment]
Thanks for reporting @altergui  :)
