### ISSUE TITLE
bug: CI github runner sometimes fails to connect to deb.debian.org:80

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#425]
since last week, the `compose-test` sometimes fails:
```
Could not connect to deb.debian.org:80 (199.232.150.132), connection timed out
```

examples:
* https://github.com/vocdoni/vocdoni-node/runs/4750624991?check_suite_focus=true#step:3:166
* https://github.com/vocdoni/vocdoni-node/runs/4748289606?check_suite_focus=true#step:3:591
* https://github.com/vocdoni/vocdoni-node/runs/4728901369?check_suite_focus=true#step:3:175
* https://github.com/vocdoni/vocdoni-node/runs/4728640708?check_suite_focus=true#step:3:216
(couldn't find any earlier failures in the last couple of months)

i found a similar issue affecting gitlab users
* https://forum.gitlab.com/t/gitlab-ci-get-timeout-from-debian-org/59040/7
* https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5590

which suggests passing `docker build --network host` to workaround (AFAIU) a MTU issue of docker-in-docker. I'll try this, but since it happens only randomly, only time will tell if it's "fixed", so I'd keep this report open for a week or so.

**Comment by altergui** [comment]
@vdo lowered the mtu for docker on both ci servers https://github.com/vocdoni/vocdoni-node/pull/426#issuecomment-1009825491
today around 11:30am UTC+1

**Comment by altergui** [comment]
just for reference, a couple more ocurrences from a few days ago:

2022-01-09T22:58:29Z 
https://github.com/vocdoni/vocdoni-node/runs/4755480647?check_suite_focus=true#step:3:166

2022-01-10T20:15:21Z
https://github.com/vocdoni/vocdoni-node/runs/4766792443?check_suite_focus=true#step:3:184

2022-01-11T09:49:33Z
https://github.com/vocdoni/vocdoni-node/runs/4773376849?check_suite_focus=true#step:3:611

this last one was today 10:49am UTC+1, just before @vdo change, let's hope it was the last one :)

**Comment by vdo** [comment]
@altergui I'm not 100% sure if the setting will be inherited in the docker-compose bridge.
If that bug happens again, add the following to the docker compose containers:
```
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
```

**Comment by altergui** [comment]
so, this did not happen again in the last 9 days, except for a single ocurrence on that same day 11/jan 12:54pm UTC+1, circa one hour after the mtu change:
2022-01-11T11:54:05Z
https://github.com/vocdoni/vocdoni-node/runs/4774810211?check_suite_focus=true#step:3:184

i have no explanation for that, but i wouldn't spend more time in this since it did not happen in the last ~23 runs (and previously was happening around 1 in 4 runs)

thanks @vdo!! :hugs:
