### ISSUE TITLE
bug: SendTokensTxCheck() won't send tokens to a non-existent account - chicken-egg problem

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#441]
If I cannot send tokens to an address, of course I cannot use it and therefore it cannot exist... but this cycle mustn't be allowed to perpetrate!

**Comment by jordipainan** [comment]
I've been talking with p4u about this and it is the expected behavior. Only existing accounts can receive tokens, so you need to create an account before being able to receive tokens.

**Comment by randomshinichi** [comment]
Let's say I want to send tokens to a new address that I just generated, but has no Account on the chain. What should be done in this case then?

**Comment by jordipainan** [comment]
With your newly generated address you create the account and once the account is created then you send the tokens.

**Comment by randomshinichi** [comment]
OK so one has to send a Tx_SetAccountInfo
