### ISSUE TITLE
bug: MintTokensTxCheck() reports "key not found" when Treasurer is undefined

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#442]
```
	// get treasurer
	treasurer, err := state.Treasurer(true)
	if err != nil {
		return common.Address{}, 0, err
	}
```
It is not obvious from the client's side what has gone wrong, and where. All he gets is an error message "key not found".

**Comment by jordipainan** [comment]
We can return a better error but I do not think is a bug. Also the Treasurer is a required piece for the ethereum-less approach, so the Treasurer must be defined on the genesis.
What we can do here is to throw an error if the Treasurer is not defined when starting a node.
