### ISSUE TITLE
Reduce ipfsSync log messages

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#460]
In DEBUG mode currently ipfsSync and its packages are flooding the log output so its very hard to find other (probably more relevant) messages.

I'd suggest to somehow add a flag to the vocdoni-node in order to configure the ipfsSync log output independently.

I'm not sure how to do that with the current log implementation, probably we need to extend the log package somehow and allow creating origin tags by log type and then be able to configure different log levels per origin. Something like:

main.go
```
log.SetOriginLogLevel("ipfsSync", "info")
```

ipfsSync.go
```
logger := log.WithOrigin("ipfsSync")
logger.Debugf("...")
```

@mvdan could probably help us here to find the best solution

**Comment by altergui** [comment]
since f83a4b2648616df9f1a4e2df009ce7d091704e74, ipfsconnect (ex-ipfsSync) is much less verbose. closing this
