### ISSUE TITLE
feature: Add `getCensusWeight`

### ISSUE THREAD

**Issue by brickpop** [vocdoni/vocdoni-node#463]
**Describe the feature**
Currently, the census service has the `getSize` call to retrieve the number of voters in a census. However, the addition of weighted censuses means that we would also need a call to know the total weight of that census.

**Motivation**
Displaying the turnout of a weighted voting election.

**Proposal**
Add a `getCensusWeight` or `getWeight` call (the second name could be ambiguous).

**Components affected**
Census Service

**Constraints & Assumptions**

**Additional information (if required)**

**Comment by jordipainan** [comment]
pending to merge #498 brickpop
