### ISSUE TITLE
bug: sometimes compose-test fails with "could not get pre-register key"

### ISSUE THREAD

**Issue by jordipainan** [vocdoni/vocdoni-node#497]
With 

`2022-02-25T11:15:48Z	FATAL	vochaintest/vochaintest.go:654	[http://gateway0:9090/dvote] could not get pre-register key main.mkTreeAnonVoteTest.func1`

**Comment by altergui** [comment]
i edited this issue  since the first line was actually reported half a year ago in #299 and i'd track it's progress there instead

i'd assume the "could not get pre-register key" is unrelated, and track progress here.

**Comment by altergui** [comment]
PR #608 merged
