### ISSUE TITLE
bug: missmatch on scrutinizer getProcessList between GW's

### ISSUE THREAD

**Issue by jordipainan** [vocdoni/vocdoni-node#509]
> `curl https://gw2.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getProcessList", "status": "ENDED", "listSize": 10, "from": 1,  "timestamp":'$(date +%s)'}}'`

`{"response":{"ok":true,"processList":["8ebfd3f3caa6f9993dbf903526a21608c133ff79f00a9cb85b2c87de34c8ed51","a7922b2d386ea24d43c37e8141e9d4941d3c3f3a01e32a19e11cb565c029bf38","9ee3f628dd229bc01bb2f87b210923368a3bc25045bc49448fbed71a21360c2c","00aa623cff84128e1d6030e254f4a8c7a56fe1521cea51219536961528a8a3ab","985e7a02382ccd2c5fd61f6b36f55073aa49a795bade7cfaf3d7b334989aa743","0cdafe81e1c6456c573444a3904a2737e0d5519a6ef6dd8deb50d375cb7f7fec","823a8339e01aaee0c732481d0891389abed8953ecc9fb122fc97634daeb93108","b6aae9b53d58a0b5705ba636f382f3a9db0aecfcd9f89259c6d6ead57bfae688","5dbb19a0240e21de661ed7223924af79a5e60ea0f5f5d9f4f7a40e17f89d2ce7","5c6c695118b3ed35db8a18cb04a21cd2119cbf8a07f9445665ca5b63436504d7"],"request":"req0024104","size":10,"timestamp":1647001464},"id":"req0024104","signature":"ae149973645f4d13e291a924f6edc16a6fb8d350ebce509e21a808d1e004afab0192bc93de93f6628938f1ba24a3c530d6e06f9901114e16215cd50754ba194400"}`

> `curl https://gw3.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getProcessList", "status": "ENDED", "listSize": 10, "from": 1,  "timestamp":'$(date +%s)'}}'`

`{"response":{"message":"no processes found for the query","ok":true,"request":"req008600","timestamp":1647001479},"id":"req008600","signature":"bb095eb191011be1cb6aedb3e0f7c5c81d3d0230e9ef35920bfde560b13a6265016cc94be89d1ffd1efc2c4ac4a6e2a160503e5fe74701d38ad44960a9645d9c00"}`

**Comment by jordipainan** [comment]
Tested with DEV environment and all gateways returns the same processes (tested with different process status), freezing this issue until "prod" code is updated.

**Comment by p4u** [comment]
Looks like getEnvelope works properly, the issue is in the explorer side.

**Comment by altergui** [comment]
fixed or irrelevant by now
