### ISSUE TITLE
feature: rename `getTxByHeight` API method

### ISSUE THREAD

**Issue by jordipainan** [vocdoni/vocdoni-node#511]
IMO it is difficult for someone to understand from the name of the function what it does, specifically the meaning of height:

`height` is that transaction's height on the Vochain as a whole, and each height value references a unique transaction. Transaction height corresponds to the order in which that transaction was mined.

So I think we can try to find a better naming.

Thoughts @emmdim @NateWilliams2 ?

**Comment by jordipainan** [comment]
Maybe `getTxByOrder` or `getTxByInclusionOrder` or `getTxByMiningOrder` ?

**Comment by emmdim** [comment]
@jordipainan I thnk the name is understandable but can one possible idea would use `height` only for blocks and use `id` for transactions

**Comment by jordipainan** [comment]
I think it can be more understandable tbh ... it is fine for me to use `id`.

**Comment by NateWilliams2** [comment]
I agree, this works for me. I'll submit a PR to vocdoni-node and docs
