### ISSUE TITLE
feature: add transaction fees to getInfo

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/vocdoni-node#522]
Add a list of the different transaction fees so a client can see the token balance needed to execute any transaction

Alternatively, add a separate endpoint specifically just for this.

@jordipainan does this make sense to you?

**Comment by jordipainan** [comment]
I think `getInfo` returns information of a specific gateway, so I am not sure that the call is intended for doing so.

Is this exposed method enough https://github.com/vocdoni/vocdoni-node/blob/master/rpcapi/accounthandlers.go#L58 ?

@NateWilliams2

**Comment by NateWilliams2** [comment]
@jordipainan I must have missed that method, didn't realize we had this already! Would you like me to add this to the docs

**Comment by jordipainan** [comment]
yes please, apologizes for not adding before
