### ISSUE TITLE
ipfsSync: replace statedblegacy by statedb or another package

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#554]
statedblegacy and graviton packages are only required by ipfsSync. 

Analyze if the migration to the current statedb is feasible (it lacks the "diff" method in order to  fetch the difference between two merkle-trees in a quick way). Else propose an alternative. Importing graviton just for ipfsSync does not look as a good approach.

**Comment by altergui** [comment]
for reference,

edu renamed statedb to statedblegacy
https://github.com/vocdoni/vocdoni-node/commit/c00444e8dd7c1e52dc737ca3a7f69335b91049c7
(at that time used by `vochain/state.go` and `ipfssync/ipfssync.go`)

and then migrated vochain to the new Arbo-based StateDB
https://github.com/vocdoni/vocdoni-node/commit/8239102c44ae09d79eb3e80b2642849bbbf0005a

by a quick look at that last commit, it does look like a big change. but i'll take deeper look.

**Comment by altergui** [comment]
fixed in f83a4b2648616df9f1a4e2df009ce7d091704e74
not by replacing it with statedb but simply dropping all the code since the package was greatly simplified
