### ISSUE TITLE
document ethereumless 

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#559]
The documentation should appear here https://docs.vocdoni.io/architecture/services/vochain.html

- [x] All new transactions (from ethereumless) should be properly documented into docs.vocdoni.net
- [x] How the accounts and token transfers (costs, burn, faucet, etc.) must be documented into docs.vocdoni.net
You can use as basis https://www.notion.so/aragonorg/Ethereum-less-vochain-description-67780a73a3e54be5892ed2a2a145b7c7
- [x] How to use vocli in order to create accounts, transfer funds, mint tokens, use faucet, etc.

**Comment by jordipainan** [comment]
Mostly done here: https://github.com/vocdoni/docs/commit/d7f141de13beb0c0c7cb661da4aec1d99afe6e1d
@randomshinichi  can you document the CLI stuff ? I'll take care of the other 2 bullet points

**Comment by jordipainan** [comment]
ping @randomshinichi

**Comment by p4u** [comment]
Hey, let's finish this please @randomshinichi

**Comment by randomshinichi** [comment]
Oops, totally forgot!
No, I didn't actually forget. vocli documentation is here: https://github.com/vocdoni/vocdoni-node/commit/50cc5fa38a762b52f07063913e3b99d409325b26

~~Guess I need to update docs.vocdoni.net though.~~
