### ISSUE TITLE
processArchive update time issue

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#562]
The processArchive is a vochain component (driven by its event system) that keeps a JSON copy of all finalized processes and publish them on IPFS by using an IPNS domain. The processArchive keeps the files forever, also after a blockchain reset, so this way the clients can still access to old voting processes and see the results.

The processArchive stores the dada into `dataDir/archive`. There is one file per process and its name is the processID. Finally there is special file named `index.json` that keeps the relation between organizationID => [ processIDs... ] in order to provide a quick way for the client to identify the processes for a specific organization.

Clients has the processArchive IPNS address hardcoded, so after fetching the blockchain list of processes they can fetch also the archived ones by performing a `fetchFile` gateway API request on `ipfs://ipns/<address>/index.json`

The IPNS record is updated on each new process and the propagated cache time (TTL) is 10 minutes. Thus once index.json is updated the content should refresh in, as maximum, 10 minutes.

Gateways and processArchive are connected through ipfsSync so the fetch and propagation time should be fine.

However we found an issue, looks like the index.json file is not updated properly. Gateways will fetch an initial copy of it and then it takes very long to update it. 

The tasks are:
- there is an LRU memory cache on the data module of vocodoni-node that stores files, this cache should either has a TTL or make a special case on `ipns` files so they are not cached
- investgate if index.json is actually not properly updated and propagated and find a solution

**Comment by altergui** [comment]
azeno is sunset, so closing this issue
