### ISSUE TITLE
bug: ECDSA signature uses v=27 on JS and v=0 on Go

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#578]
Currently a signature made in dvote-js produces a different public key than intended in the go code. This is because an ECDSA signature is made up of R, S, V. V is 1 byte.

Ethereum varies V according to chainID to prevent tx replay attacks across differnt chains. Of course, they can do this because chainID is a number for them.

This message is signed:
```
Vocdoni signed transaction:

4773a54f510852032e288a256da444d67c263fe176b9781923746b889aa97a58
```
```
JS
12c78429794bb0876a196bc4e1d5a01c6c247607a75ad2845452b2261152342e2ab60af589127a8dbf667e3f1bf9a861286680fc5456aa0f5223f8f55c2465ef1b
GO
12c78429794bb0876a196bc4e1d5a01c6c247607a75ad2845452b2261152342e2ab60af589127a8dbf667e3f1bf9a861286680fc5456aa0f5223f8f55c2465ef00
```

1b is 27base10.
[MyCrypto's guide to ECDSA signatures](https://medium.com/mycrypto/the-magic-of-digital-signatures-on-ethereum-98fe184dc9c7)
[Why 27](https://github.com/ethereum/go-ethereum/issues/19751)
[EIP-155](https://eips.ethereum.org/EIPS/eip-155)

We should agree on something.
@p4u @jordipainan @emmdim @G10h4ck @altergui 

Also why haven't we encountered this yet, what is production running?

**Comment by randomshinichi** [comment]
Somehow it started working. Some things I did: restore original package.json. Maybe chainID was silently different now.
Maybe the real issue is that when v is derived, the node doesn't check if it's the same as its own chainID.
```
=================Going to sign=================
Vocdoni signed transaction:

dc9ba717958fe390ad8eedec2286b9bb9965456b0533667258802e5257537321
===============================================
Account.setAccountInfo(): signature 0x92fa67b475db46ee8e067a5bde1fd221a302f0a2cdf0ddde6f1fe3afe6a4a6cd3a1d01bbabcf189d125a3a2de3c8d12e7852d91229fb25ee034df47178ebf6121b
```
Signature is still 1b from JS side.

**Comment by p4u** [comment]
I'm pretty sure using the correct versions of the packages and backend solves the issue. Else everything would be broken right now. Maybe @marcvelmer can help here.

What endpoints are u using for testing? Ara you working on the Development network?

**Comment by randomshinichi** [comment]
It turned out to be chain IDs not matching, but this seems to be the real problem

https://github.com/vocdoni/vocdoni-node/issues/579

Basically chain ID can be blank, which results it in being undefined in the JS SDK.

Im using voconed
