### ISSUE TITLE
bug: chainID can be blank, but this causes undefined/unexpected behaviour

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#579]
**Describe the bug**
In this [api/types.go:172](https://github.com/vocdoni/vocdoni-node/blob/74742a36aa987c0f7af15b2b3225f01866e61381/api/types.go#L172), chainID can be omitted if it is not relevant to the API request.

However, there is no way to set the chainID normally, which means that by default, the node is running a chainID of `""`. This causes the Go node to report `""` for chainID, but since it is omitempty, it omits that field even when the request is `getInfo`. Then the JS SDK thinks the chainID is `undefined`.

Also, chainID should be a number, not a string,  because [EIP-155](https://eips.ethereum.org/EIPS/eip-155) says `v` is calculated from the chainID.

> If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process
One cannot do this for strings. It has worked so far but to avoid future headaches, we should clean this up.

https://gw1.vocdoni.net/dvote -> 'undefined'
https://gw1.dev.vocdoni.net/dvote -> 'vocdoni-development-67'

**Comment by jordipainan** [comment]
The idea is that the chainID is defined into the genesis, so a network is started with a given chainID when the genesis is read/created.
The query you are making at `gw1.vocdoni.net/dvote` returns a blank chainID cause is a release from 9 months ago, the current production release is azeno.

```bash
curl https://gw1-azeno.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getInfo", "timestamp":'$(date +%s)'}}'
{"response":{"apiList":["file","census","vote","results","indexer"],"chainId":"azeno","health":81,"ok":true,"request":"req0023091","timestamp":1658137581},"id":"req0023091","signature":"1d2b261ac8c7a538ad6f458cc3af29ddbbf21005f8405d634e7e0b2ac11b8be408517ee48a40bba5eb7d2cb600aa7ca0602b5aff2f9302386f588efe82aabb2c00"}
```
The unexpected behavior is not on the gateway but in dvote-js that is not taking into account if a chainID is unknown.
Also you are using voconed which is kind of a stripped version of a proper node and does not fail on startup with a blank chainID, we can change that btw :)

Finally is not mandatory for the chainID to be a number as we are not following the EIP-155 spec. In this case we use a string which is enough for signing vocdoni txs (! eth transactions).

**Comment by jordipainan** [comment]
going to open an issue for requiring voconed to have a chainID set :)

**Comment by randomshinichi** [comment]
>  as we are not following the EIP-155 spec

You can't say this and then use ethereum libraries unmodified because they're following the EIP-155 spec! or whatever spec they're following - the Go library likes to end signatures with v=0 or 1, and ethersjs likes to end signatures with v=27 or 28.Why aren't they the same, don't ask me
