### ISSUE TITLE
Wrong var type on log prints

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#589]
There is one here.
```
2022-07-20T16:49:12Z	DEBUG	census/importqueue.go:59	retrieved census with rootHash ̑��]Mu#�����G�,��b���\�N@�� and size 254 bytes
```

But probably there are more. It would be nice if we find a linter or a tool to find these string formating mistakes automatically (and even better if we can add it to the tests).

**Comment by altergui** [comment]
i spent a much more time than expected with this, and was about to desist, but then came up with #590 
ironically it doesn't catch that particular log line, but i couldn't imagine a programmatical way of defining a "formatting mistake" (%s to print a []byte could be perfectly valid, but it's not, in this case, because of the *content* of that []byte)

**Comment by altergui** [comment]
well, nice enough, (and TBH unexpected! since it's happening on `go vet`) it did catch a couple of bugs. hurray!
https://github.com/vocdoni/vocdoni-node/runs/7566037480?check_suite_focus=true
```
# go.vocdoni.io/dvote/ethereum/ethevents
ethereum/ethevents/handlers.go:335:2: Debugf format %s reads arg #2, but call has 1 arg
# go.vocdoni.io/dvote/cmd/vochaintest
cmd/vochaintest/vochaintest.go:1625:2: Info call has possible formatting directive %s
```

**Comment by altergui** [comment]
going back to the original issue, i manually inspected the code with some keywords (things that are most likely []byte)
```
git grep 'log.' | grep -i hash
git grep 'log.' | grep -i root
git grep 'log.' | grep -i %s
```
and spotted some other cases, fixed them

**Comment by altergui** [comment]
and many more with Fatal (which i initially did not touch)
```
# go.vocdoni.io/dvote/vochain
vochain/app.go:496:4: Fatal call has possible formatting directive %s
# go.vocdoni.io/dvote/client
client/api.go:584:4: Fatal call has possible formatting directive %s
client/api.go:790:4: Fatal call has possible formatting directive %s
# go.vocdoni.io/dvote/ethereum/ethevents
ethereum/ethevents/events.go:319:17: Fatalf call has arguments but no formatting directives
# go.vocdoni.io/dvote/cmd/vochaininspector
cmd/vochaininspector/inspector.go:300:4: Fatalf call has error-wrapping directive %w, which is only supported by Errorf
```

reaaaaally nice

**Comment by altergui** [comment]
#590 merged and fixed this
