### ISSUE TITLE
races on ethereumless testing

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#606]
There seems to be some races on the ethereumless tests. 

This one is happening quite often now: https://github.com/vocdoni/vocdoni-node/actions/runs/3097110738

Another one reported by @altergui  https://github.com/vocdoni/vocdoni-node/issues/575

We need to fix this ASAP, all developments are slowed if the CI is constantly failing. Thanks.

**Comment by altergui** [comment]
i did collect that one as well https://github.com/vocdoni/vocdoni-node/issues/575#issuecomment-1173995386
and promised that i'd do it but didn't prioritize it

i renamed the original bug to encompass both issues, since there's more info in the original report i'd close this as dup

**Comment by altergui** [comment]
closing this in favor of #575
