### ISSUE TITLE
Staticcheck fails

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#613]
Can we find a workaround for this issue? Its happening quite often.

![image](https://user-images.githubusercontent.com/1075446/192013374-92f285ec-d27c-459b-9788-18a7af1fcd4d.png)

**Comment by p4u** [comment]
@mvdan

**Comment by altergui** [comment]
i've noticed a pattern, that it's only one of the runners: 'hetzner-ci-2' consistently fails and the other runners run staticcheck just fine.

interestingly enough, 'hetzner-ci' (which runs on the same metal) does not fail.
https://github.com/vocdoni/vocdoni-node/actions/runs/3114003265/jobs/5049563674

**Comment by altergui** [comment]
indeed. cache dir was corrupted
https://github.com/vocdoni/vocdoni-node/actions/runs/2999010054/jobs/5075757135#step:4:14

silly me: when i "fixed" this a couple of weeks ago #449 i did not realise each runner had a different "filesystem" and each one of them needed to run the fix

doing it now

**Comment by altergui** [comment]
my brilliant fix :stuck_out_tongue:  was only run on runner 'ci' https://github.com/vocdoni/vocdoni-node/actions/runs/2999095150/jobs/4812433855#step:4:10
and not on ci2, hetzner-ci, hetzner-ci2, hetzner-ci3

fixed everything now

**Comment by altergui** [comment]
hetzner-ci-2 is running staticcheck successfully now 
https://github.com/vocdoni/vocdoni-node/actions/runs/3001400866/jobs/5075954855#step:8:1
