### ISSUE TITLE
ci: scrutinizer test sometimes times out

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#617]
for example
https://github.com/vocdoni/vocdoni-node/actions/runs/3137078872/jobs/5094797704#step:5:393
```
panic: test timed out after 1m0s

goroutine 252826 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0004d1380, {0x159d2f3?, 0x52e245?}, 0x18b1ae8)
	/usr/local/go/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0004d1380?)
	/usr/local/go/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc0004d1380, 0xc0001fbca0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0006be280?, {0x2322380, 0xd, 0xd}, {0x7f2725902a68?, 0x40?, 0x23e3c40?})
	/usr/local/go/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0006be280)
	/usr/local/go/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:133 +0x255

[...]

goroutine 248826 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:194 +0x12e
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).computePendingProcesses(0xc01d398780, 0xebe2780?)
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:360 +0x77
created by go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).Commit
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer.go:471 +0xf25
FAIL	go.vocdoni.io/dvote/vochain/scrutinizer	60.569s
```

another example (basically same output):
https://github.com/vocdoni/vocdoni-node/actions/runs/3137079128/jobs/5094798365#step:5:378

both runs happened in the slowest build server (ci2), this same server sometimes manages to run the test successfully. maybe the difference is whether is under load or not. but anyway we should either dig into this or at the very minimum increase the timeout of this test, so it's not flaky anymore.

**Comment by altergui** [comment]
mmh... happened again but this time on a run on the faster server (hetzner-ci)
https://github.com/vocdoni/vocdoni-node/actions/runs/3137843613/jobs/5096492998

**Comment by altergui** [comment]
vochain test also sometimes takes longer than 60 seconds and times out
https://github.com/vocdoni/vocdoni-node/actions/runs/3141870044/jobs/5104802233#step:5:1391
```
FAIL	go.vocdoni.io/dvote/vochain	61.242s
```

**Comment by mvdan** [comment]
I'll look into this since I'm already doing https://github.com/vocdoni/vocdoni-node/issues/616.
