### ISSUE TITLE
vochain/scrutinizer: sql create process: database is locked

### ISSUE THREAD

**Issue by mvdan** [vocdoni/vocdoni-node#642]
Flake from https://github.com/vocdoni/vocdoni-node/actions/runs/3329285774/jobs/5506310035:

```
2022-10-26T13:18:51Z	ERROR	scrutinizer/scrutinizer.go:355	commit: cannot create new empty process: sql create process: database is locked
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).Commit
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer.go:355
go.vocdoni.io/dvote/vochain.(*State).Save
	/__w/vocdoni-node/vocdoni-node/vochain/state.go:1059
go.vocdoni.io/dvote/vochain.(*BaseApplication).Commit
	/__w/vocdoni-node/vocdoni-node/vochain/app.go:534
go.vocdoni.io/dvote/vochain.(*BaseApplication).AdvanceTestBlock
	/__w/vocdoni-node/vocdoni-node/vochain/app.go:467
go.vocdoni.io/dvote/vochain/scrutinizer.testProcessList
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer_test.go:213
go.vocdoni.io/dvote/vochain/scrutinizer.TestProcessList
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer_test.go:175
testing.tRunner
```

We likely need to tweak the way we use multiple connections to sqlite so that we don't run into locking issues.

**Comment by p4u** [comment]
I think we should figure out some solution (even if temporary) for this issue. Can we check the error and if matches, retry the transaction @mvdan ?

**Comment by mvdan** [comment]
The solution isn't hard, should just be a few lines. I just want to properly test it.

**Comment by altergui** [comment]
> I think we should figure out some solution (even if temporary) for this issue. Can we check the error and if matches, retry the transaction @mvdan ?

i shamelessly did exactly this in some test.
https://github.com/vocdoni/vocdoni-node/blob/1351ec03ae76ea8990e63436b537d79a0fdfed3d/client/api.go#L239-L244
a general solution would be just great
