### ISSUE TITLE
[Oracle] Support Bridge processes on the `UpdateCensus` transaction

### ISSUE THREAD

**Issue by brickpop** [vocdoni/vocdoni-node#7]
When a Bridge process has been created, submit a second transaction to signal the ERC20 census

- [ ] Fetch the storage proof
- [ ] Add new fields that allow updating the ERC20 census
    - [ ] Eth block height, index slot, state root
    - [ ] Proof that the update is legit
- [ ] State proof ⇒ Storage proof

**Comment by jordipainan** [comment]
Approach for this was changed: https://hackmd.vocdoni.net/kZ-22zfmSMa5CTnwwyyLVg#
Commit: https://github.com/vocdoni/go-dvote/commit/6b1fdf9d62ee70778f49ad53edd190406302a2a3

Pending: Check storage proof. The address needs to be extracted from the `paramsSignature` field of the process.
