### ISSUE TITLE
Store the txHash into the indexer table voteRef

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#764]
Store the txHash into the indexer voteRef so we don't need to access the tendermint blockstore anymore on GetEnvelope() and GetEnvelopes()

**Comment by mvdan** [comment]
What about WalkEnvelopes? It's a fairly expensive iterator since it has to get data from the blockstore for every item.

**Comment by p4u** [comment]
This behavior is already changed. Now WalkEnvelopes takes the data from the state merkle tree, which is much more faster.
