### ISSUE TITLE
bug: persistant error launching the vochain on local

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/vocdoni-node#768]
**Describe the bug**
This morning I merged master with the branch `feature/new_prover_integration` and from this moment I got an error trace that is printed every time:
`ERR go.vocdoni.io/dvote/vochain/indexer/indexer.go:499 > commit: cannot create new token transfer error="UNIQUE constraint failed: token_transfers.tx_hash"`

**To Reproduce (please complete the following information)**

- Steps to reproduce the behavior:
  1. Go to dockerfile/testsuite on `feature/new_prover_integration` branch.
  2. Start a local stack with: `docker-compose up -d && docker-compose logs --follow`

**Expected behavior**
That error does not produce any unexpected behavior, but simply it was not there before.

**System (please complete the following information):**

- OS: Linux voceloni 5.10.0-18-amd64 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
- Software version: Docker version 20.10.22, build 3a2c30b; Go 1.18.10
- Commit hash: 866ac38690639e0ddcb09f4f117a5547b455845f

**Comment by jordipainan** [comment]
@lucasmenendez Did you reset the blockchain but you did not delete the indexer database ? The indexer is trying to add the same transfer identifier twice and as is a DB primary key that is unique you're getting this error

**Comment by lucasmenendez** [comment]
@jordipainan Probably not. Deleting docker volumes is not enough?

**Comment by jordipainan** [comment]
@lucasmenendez should be, but try to use --remove-orphans because this error is quite strange if is not generated by what I'm commenting.

**Comment by lucasmenendez** [comment]
@jordipainan I tried removing orphans and when I try to start a new election the error appears again:

- Starting the nodes with: `docker-compose down -v --rmi all --remove-orphans && docker-compose build && docker-compose up -d && docker-compose logs --follow`
- Starting a election with: `go run ./cmd/end2endtest --host=http://0.0.0.0:9090/v2 --faucet=http://0.0.0.0:9090/v2/faucet/dev/ --logLevel=debug --operation=vtest --votes=200`

**Comment by jordipainan** [comment]
Solved :)
