### ISSUE TITLE
migrate to tendermint v0.37

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#777]
keep an eye out for the release plan https://github.com/tendermint/tendermint/issues/9091 and upgrade our code when the time comes

**Comment by mvdan** [comment]
@jordipainan I guess any plans for future releases in that repo are scrapped now, right? I think there were plans for a "v2" rewrite of tendermint in another thread.

**Comment by altergui** [comment]
indeed @jordipainan shared this tweet, thanks!!!

https://twitter.com/informalinc/status/1620825636213526528?t=Aci1dzAbVNyiNkgb-M5-fw&s=35

1/ Today we announce the launch of CometBFT, a state machine replication engine for the interchain!

CometBFT is a fork and successor of Tendermint Core, stewarded by [@informalinc](https://twitter.com/informalinc)
 and supported by [@interchain_io](https://twitter.com/interchain_io)
 on behalf of the wider [@cosmos](https://twitter.com/cosmos)
 
https://github.com/cometbft/cometbft

**Comment by jordipainan** [comment]
> @jordipainan I guess any plans for future releases in that repo are scrapped now, right? I think there were plans for a "v2" rewrite of tendermint in another thread.

Hey, sorry @mvdan did not see this one. Yes, all *v2 is mostly abandoned … plus what altergui commented, seems that cometbft is now the reference repo. We still need to see how thing evolve and decide if we do our stuff, or we continue with cometbft or we switch to another fork that might be more suited for our use case.

That said, and after talking about it with other team members, we think that there is no major reason in the short term for not staying with the current version. It works and accomplished its purpose, pretty well.
Moreover, the roadmap planned for 2023 is 100% achievable and there are lots of more urgent things are on the table. You also have the example of Polygon, whose consensus layer is running a 2.5 y/o Tendermint-Core version with Heimdall (still up and running without any major issues).

What I'm writing here can change, but for now, summarizes the current state of the art :)
I hope this helps to have more context.

**Comment by jordipainan** [comment]
Let's keep this issue open for chatting about it.

**Comment by mvdan** [comment]
Done in https://github.com/vocdoni/vocdoni-node/pull/909, I think.
