### ISSUE TITLE
bug: benchmarks not working

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#78]
**Describe the bug**
The current existing benchmarks are not working.

**To Reproduce (please complete the following information)**
`go test -bench=.`

**Current behavior**
Both Vochain benchmarks have errors

**Expected behavior**
It should work

**System (please complete the following information):**
...

**Additional context**
...

**Comment by p4u** [comment]
WIP: https://github.com/vocdoni/vocdoni-node/pull/77

**Comment by jordipainan** [comment]
Update status

```bash
--- FAIL: BenchmarkVochain
    vochain.go:216: starting vochain scrutinizer
    vochain_benchmark_test.go:201: proof not generated while it should be generated correctly
```
