### ISSUE TITLE
api: elections/count and total transactions

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#792]
Perform the following modifications to the API
- [] add new endpoint /elections/count
- [] extend chain/info so it includes the total count of transactions

Open the issues on interoperability so SDK and Docs update.

**Comment by jordipainan** [comment]
> add new endpoint /elections/count 

What this method returns? The total process count of a given organization or the total process count of all organizations?
If it is the later why we want to have 2 endpoints that return the same info? The consumer can just use chain/info.

Thank you! @p4u

**Comment by p4u** [comment]
The total since the election count for an org is already available.

**Comment by p4u** [comment]
Sorry @jordipainan my initial description was wrong. There is no need to duplicate the transaction count in two different endpoints.

**Comment by p4u** [comment]
So, I'm being very confusing, sorry. 

I'd just extend `/chain/info` with the total number of elections and transactions. That's it.

**Comment by jordipainan** [comment]
just saw this message, oki!
