### ISSUE TITLE
api: handle errors in an idiomatic way

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#802]
in commit https://github.com/vocdoni/vocdoni-node/commit/2464a8340617e468b77eae11018c52549b515565 it became evident we could handle errors better
@jordipainan suggested using constants.

at some point we need to match strings, since it's a reply coming from an API. but the idea would be as soon as possible to turn that into a native `error` and use golang error wrapping and matching facilities.

i'm happy to implement something along those lines.
@mvdan you most likely have some valuable pointers, opinion or ready-made solution?

**Comment by mvdan** [comment]
Assuming that this is an error string being returned by our server on an API request, we could make the indexer (which uses sqlite) catch "not found" errors returned by sqlite, and return those as a special error code to our API clients - akin to an HTTP 404.

**Comment by altergui** [comment]
now the first part is merged, the remaining task would be to somehow assign HTTP error codes (404 for example) to some of the errors. i'll explore this today and propose a PR

**Comment by altergui** [comment]
second part done.

apiclient is still untouched, until now i've focused on the api part, and reporting this in interop so that the SDK can adapt to those changes.

i'll start with integrating this apiclient now, if there are no objections

**Comment by altergui** [comment]
apiclient still pending, that second PR was totally half-baked and i fixed it in #832 , also added unit tests
