### ISSUE TITLE
bug: maxVoteOverwrite seems not be a strict constraint 

### ISSUE THREAD

**Issue by mariajdab** [vocdoni/vocdoni-node#877]
**Describe the bug**
That is related with the test `voteoverwritenotwaitnextblock`: tries to check that the `MaxVoteOverwrite` feature is correctly implemented, even if a vote is consecutive overwrite without wait until the next block, and doesn't have time to validate and raise the error:  `checkTx: overwrite count reached` .

After run the test around 100 times with different `--votes` flags it passed around 97 time but failed 3 times with wrong resutls due it's taking as a valid vote the second overwrite and the test has the `MaxVoteOverwrite = 1`

**To Reproduce (please complete the following information)**

- git checkout feat/voteOverwriteTest
- Steps to reproduce the behavior:
  1. run multiples times the test `voteoverwritenotwaitnextblock`:
  ` go run ./cmd/end2endtest --host=https://api-dev.vocdoni.net/v2 --logLevel=debug --votes=100 --operation voteoverwritenotwaitnextblock`

![Screenshot from 2023-04-06 13-50-54](https://user-images.githubusercontent.com/48325352/230482647-b88f9cd1-86ba-484b-b30e-9f31db64e292.png)

**Comment by p4u** [comment]
If I'm correct, we found this bug was actually a race on the indexer, but not a bug of the internal Vochain state. 
So we need a apiclient method that ensures we actually retrieve the final results. 
Am I correct?

**Comment by mariajdab** [comment]
> If I'm correct, we found this bug was actually a race on the indexer, but not a bug of the internal Vochain state. So we need a apiclient method that ensures we actually retrieve the final results. Am I correct?

Yeah, you are right and the method is already created: [commit](https://github.com/vocdoni/vocdoni-node/commit/513be3f76341ff8af6c67669d8325b8881b5bba9). It just necessary to add more `context.WithTimeout` due 60 sec causes a `context deadline error: never reached status results`, it happens for example, when votes=100 o more. I think the bug could be closed
