### ISSUE TITLE
api: `/elections/{electionID}` reports results when it shouldn't

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#883]
```
curl -s https://api-dev.vocdoni.net/v2/elections/c5d2460186f729225702eaa9ddd8f341c18bbfd761a0b17d9002020000000000/scrutiny | jq .|head -n 20
```
gives
```
{
  "error": "election results are not yet available",
  "code": 5024
}
```

but

```
curl -s https://api-dev.vocdoni.net/v2/elections/c5d2460186f729225702eaa9ddd8f341c18bbfd761a0b17d9002020000000000 | jq . | head -n 20
```

returns results

```
{
  "electionId": "c5d2460186f729225702eaa9ddd8f341c18bbfd761a0b17d9002020000000000",
  "organizationId": "29225702eaa9ddd8f341c18bbfd761a0b17d9002",
  "status": "ENDED",
  "startDate": "2023-04-10T17:25:15.479865131Z",
  "endDate": "2023-04-17T21:53:59.857503671Z",
  "voteCount": 10,
  "finalResults": true,
  "result": [
    [
      "50",
      "50",
      "0"
    ]
  ],
  "census": {
    "censusOrigin": "OFF_CHAIN_TREE_WEIGHTED",
    "censusRoot": "db26703fc622a9ed64a40c3f06ad7a2949b45ad23456564eaa0f781eed0b615f",
    "postRegisterCensusRoot": "",
    "censusURL": "ipfs://bagaaieraklzysqogpsw3xsaqaa3ohnlbayjpxwwap26c7hz2yeyzy2jesjra",
```

worst of all, "finalResults=true"

AFAIU, `/scrutiny` endpoint queries the state
but `/elections/{electionID}` queries the indexer to construct the `result` field

### what should happen

`/elections/{electionID}` should return the same information as `/elections/{electionID}/scrutiny`, i.e. no results. or at the very least, report partial results but with `finalResults=false`

**Comment by altergui** [comment]
in that case, the string `election results are not yet available` should be clarified as in `election final results are not yet available`

**Comment by p4u** [comment]
I think this issue could be closed. @altergui ?

**Comment by altergui** [comment]
indeed, i just checked and now   `"finalResults": false` during state ENDED, and only when state changes to RESULTS (and scrutiny starts returning the final results) is "finalResults=true"

i have no idea exactly when this was fixed but this can definitely be closed now
