### ISSUE TITLE
Remove treasurer logic

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#896]
Instead of using the treasurer, we would just fund an address with tokens on the genesis file.

**Comment by altergui** [comment]
started working on this, and realized the treasurer not only deals with token creation but also is the only way to set tx costs (after genesis)

is there a plan regarding that regression?

**Comment by p4u** [comment]
~~The treasurer adds complexity to the internal logic, and we are trying to simplify the overall architecture.~~

~~The treasurer as an actor, able to mint new tokens in the Vochain is hard to explain and justify~~

~~Instead, the validators should be the ones receiving rewards per block and providing the tokens to those who need to use them.~~

~~In addition, the validators would need a governance mechanism, to increase the base transaction cost.~~

~~For now, I think it is fine to have a hard-coded transaction cost in the Genesis file.~~

EDIT: umm, ok. I think this requires a further discussion, so let's not advance on this issue for now.
