### ISSUE TITLE
end2endtest: do not stop sending votes if mempool full

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#922]
When voting, if the error received is "mempool is full", wait for some time (at least 1 block time) and try again.

`2023-05-12T22:40:19.272+02:00 WRN end2endtest/helpers.go:365 > API error: 500 (mempool is full: number of txs 20000 (max: 20000), total txs bytes 14358904 (max: 2048000000)`

**Comment by altergui** [comment]
fixed in #974
