### ISSUE TITLE
Panic on big unmarshal

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#967]
panic: math/big: cannot unmarshal "<nil>" into a *big.Int

goroutine 290402 [running]:
go.vocdoni.io/dvote/types.(*BigInt).UnmarshalText(...)
	go.vocdoni.io/dvote/types/big.go:17
go.vocdoni.io/dvote/vochain/indexer/indexertypes.decodeBigint({0xc003139eb0, 0x5})
	go.vocdoni.io/dvote/vochain/indexer/indexertypes/types.go:148 +0x8f
go.vocdoni.io/dvote/vochain/indexer/indexertypes.ResultsFromDB(0xc006e39980)
	go.vocdoni.io/dvote/vochain/indexer/indexertypes/types.go:126 +0x54
go.vocdoni.io/dvote/vochain/indexer.(*Indexer).GetResults(0x3279020?, {0xc00a90b340?, 0x5?, 0x40?})
	go.vocdoni.io/dvote/vochain/indexer/vote.go:169 +0xe5
go.vocdoni.io/dvote/api.(*API).electionHandler(0xc00170bb90, 0xc007e74024?, 0xc00086bd80)
	go.vocdoni.io/dvote/api/elections.go:218 +0x7bf
go.vocdoni.io/dvote/httprouter/apirest.(*API).RegisterMethod.func1({{0x30f7f40, 0xc0044f5890}, {0xc115e8049486830f, 0x8b9efe328, 0x559bf00}, {0xc001fdfcd0, 0x3, 0x3}, 0xc00086bd80})
	go.vocdoni.io/dvote/httprouter/apirest/apirest.go:209 +0x74
created by go.vocdoni.io/dvote/httprouter.(*HTTProuter).routerHandler.func1
	go.vocdoni.io/dvote/httprouter/httprouter.go:261 +0x3f2

**Comment by mvdan** [comment]
36a976102d3bfb15379be4be85c4b72f1155ef8b made `decodeBigint` not panic on empty strings already; I think this was an older deploy.
