### ISSUE TITLE
Improved Performance in go-libp2p-kad-dht: New Feature Reduces PUT/Provide Latencies to <1s

### ISSUE THREAD

**Issue by dennis-tra** [vocdoni/vocdoni-node#989]
Hi vocdoni Devs,

This is Dennis from Protocol Labs. I wanted to inform you about an exciting update regarding the [`go-libp2p-kad-dht`](https://github.com/libp2p/go-libp2p-kad-dht) implementation, which I believe you are currently using (at least indirectly via libipfs/boxo?). As part of our continuous efforts to enhance performance, we have introduced a new experimental feature that significantly improves the PUT/Provide latencies.

Previously, the DHT's PUT performance was known to be rather sluggish, often taking more than 10 seconds or even minutes. However, with the latest release of `go-libp2p-kad-dht` >v0.23.0, we have introduced a feature called "Optimistic Provide" [[Kubo documentation](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#optimistic-provide)]. This feature has demonstrated great results, bringing the latencies down to less than 1 second in the 50th percentile and less than 1.4 seconds in the 90th percentile.

While I'm unaware of the specific requirements of your use case or whether the previous latencies posed any challenges for you, I wanted to ensure that you are aware of this improvement.

If you have any questions or would like more information about this new feature, please don't hesitate to reach out.

Cheers,
Dennis

**Comment by p4u** [comment]
Thanks @dennis-tra for the hint, this is great news.
We use libp2p KAD for node discovery and clustering (we call it ipfsConnect) and also boxo for retrieving/publishing files.

Let's upgrade to v0.23.0

**Comment by altergui** [comment]
we're indeed using `v0.23.0`

https://github.com/vocdoni/vocdoni-node/blob/8e7a65b9a378e49fde552bda44631c171ffb40ef/go.mod#L196

that according to https://github.com/libp2p/go-libp2p-kad-dht/releases/tag/v0.23.0 already includes the new feature

so i'm closing this, AFAIU from reading the docs there's nothing we need to do besides using v0.23.0
in case i'm wrong (for example we need to enable some flag) please reopen

**Comment by dennis-tra** [comment]
You indeed need to explicitly enable it by passing the `EnableOptimisticProvide` flag to the DHT constructor.

https://github.com/libp2p/go-libp2p-kad-dht/blob/a497df16a4d174ffaf5844e3b4de8cc6f607da18/dht_options.go#L331

**Comment by altergui** [comment]
i spent a while trying to figure this out, without success. Here's how we construct the node

https://github.com/vocdoni/vocdoni-node/blob/af85c0571e2834cf85a1906e1ece99c12f8939a2/data/ipfs/init.go#L79-L93

in ipfsconnect we just reuse that same host. the `*core.IpfsNode` returned by the `ipfscore.NewNode()` above ends up in `s.node`
https://github.com/vocdoni/vocdoni-node/blob/af25ad88fd8d2a7b4136be03e1bc24dd788e4c31/subpub/discovery.go#L29

**Comment by altergui** [comment]
I understand that if we were constructing the node with `libp2p.New()` (as in https://github.com/libp2p/go-libp2p/blob/master/examples/libp2p-host/host.go)
we'd do something like
```
	libp2p.New( 
           // whatever opts...
	
	   // Let this host use the DHT to find other hosts
		libp2p.Routing(func(h host.Host) (routing.PeerRouting, error) {
			idht, err := dht.New(context.TODO(), h,
                        dht.EnableOptimisticProvide()) // <-----
			return idht, err
		}),
	)
```

but unfortunately that's not our case, and i get really lost on the "huge number of ways to set these up" (sic https://github.com/libp2p/go-libp2p/tree/master/examples/libp2p-host)
any pointers very much appreciated @dennis-tra

**Comment by dennis-tra** [comment]
Hey @altergui, you could try the following:

```go
cfg := &ipfscore.BuildCfg{
	Repo:      r,
	Online:    true,
	Permanent: true,
	Routing: func(args libp2p.RoutingOptionArgs) (routing.Routing, error) {
		args.OptimisticProvide = true
		return libp2p.DHTOption(args)
	},
}
```

I'm also not super familiar with the `ipfscore` package but I just checked the code. Because you're not setting the `Routing` field it defaults to `libp2p.DHTOption`, so adjusting the args and then passing them through should activate the feature.
